## Run `yarn config -v` to see a full list of all possible keys & their current values
cacheFolder: "./.yarn/cache"
nodeLinker: "pnp"
# need to specify this so that we can cache packages locally & for CI
# see: https://github.com/yarnpkg/berry/discussions/3872
supportedArchitectures:
  os:
    - "current"
    - "linux"
  cpu:
    - "current"
    - "x64"
# satisfies some warnings about peer dependencies that are included in the repo
packageExtensions:
  next-drupal-query@*:
    dependencies:
      react: "^18"
      react-dom: "^18"
  "@department-of-veterans-affairs/component-library@*":
    dependencies:
      react: "^18"
      react-dom: "^18"
