nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

supportedArchitectures:
  cpu:
    - 'current'
    - 'x64'
  os:
    - 'current'
    - 'darwin'
    - 'linux'
  # ensures all packages included for CI envs
  libc:
    - 'glibc'
    - 'musl'

yarnPath: .yarn/releases/yarn-3.6.1.cjs

enableScripts: true

# satisfies some warnings about peer dependencies that are included in the repo
packageExtensions:
  next-drupal-query@*:
    dependencies:
      react: "^18"
      react-dom: "^18"
  "@department-of-veterans-affairs/component-library@*":
    dependencies:
      react: "^18"
      react-dom: "^18"
  "@openfeature/server-sdk@*":
    dependencies:
      "@openfeature/core": "^1.9.0"
