nodeLinker: node-modules
# need to specify this so that we can cache packages locally & for CI
# see: https://github.com/yarnpkg/berry/discussions/3872
supportedArchitectures:
  os:
    - "current"
    - "linux"
  cpu:
    - "current"
    - "x64"
