compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

supportedArchitectures:
  cpu:
    - current
    - x64
  libc:
    - glibc
  os:
    - current
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.0.2.cjs
