compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  "@department-of-veterans-affairs/component-library@*":
    dependencies:
      react: ^18
      react-dom: ^18
  "@storybook/addon-controls@*":
    dependencies:
      react: ^18
      react-dom: ^18
  "@storybook/manager-api@*":
    dependencies:
      react: ^18
      react-dom: ^18
  next-drupal-query@*:
    dependencies:
      react: ^18
      react-dom: ^18

supportedArchitectures:
  cpu:
    - current
    - x64
  libc:
    - glibc
    - musl
  os:
    - current
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.2.2.cjs
