nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - current
    - x64
  os:
    - current
    - linux

yarnPath: .yarn/releases/yarn-3.6.3.cjs
enableGlobalCache: false
enableTelemetry: false
