version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      # UI port
      - '16686:16686'
      # OTLP HTTP receiver (what Next.js uses)
      - '4318:4318'
      # OTLP gRPC receiver
      - '4317:4317'
      # Jaeger agent ports for other SDKs
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      # Jaeger collector ports
      - '14250:14250'
      - '14268:14268'
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    volumes:
      - jaeger-data:/badger
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:16686/']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tracing

networks:
  tracing:
    driver: bridge

volumes:
  jaeger-data:
