import { VetCenterOutstation } from './formatted-type'

export const mockData = {
  address: {
    langcode: 'en',
    country_code: 'US',
    administrative_area: 'PA',
    locality: 'Pittsburgh',
    postal_code: '15215',
    address_line1: '1010 Delafield Road',
    address_line2: '',
  },
  ccNonTraditionalHours: {
    id: '1',
    type: 'paragraph--wysiwyg' as const,
    html: '<p>We also have non-traditional hours.</p>',
  },
  ccVetCenterCallCenter: {
    id: '1',
    type: 'paragraph--wysiwyg' as const,
    html: '<p>Our call center is available 24/7.</p>',
  },
  ccVetCenterFaqs: {
    type: 'paragraph--q_a_section' as const,
    id: '5f582f12-b72f-4a35-a9df-411485c8e446',
    header: 'FAQs',
    intro: 'Select a topic to learn more.',
    displayAccordion: true,
    questions: [],
  },
  geolocation: {
    value: 'POINT (-80.05719073 40.42665609)',
    geo_type: 'Point',
    lat: 40.42665609,
    lon: -80.05719073,
    left: -80.05719073,
    top: 40.42665609,
    right: -80.05719073,
    bottom: 40.42665609,
    geohash: 'dppjfr2nk4zuym',
    latlon: '40.42665609,-80.05719073',
  },
  featuredContent: [],
  introText: 'Test introText',
  officeHours: [
    { day: 0, starthours: null, endhours: null, comment: 'Closed' },
    { day: 1, starthours: 800, endhours: 1630, comment: '' },
    { day: 2, starthours: 800, endhours: 1630, comment: '' },
    { day: 3, starthours: 800, endhours: 1630, comment: '' },
    { day: 4, starthours: 800, endhours: 1630, comment: '' },
    { day: 5, starthours: 800, endhours: 1630, comment: '' },
    { day: 6, starthours: null, endhours: null, comment: 'Closed' },
  ],
  officialName: 'Test Name',
  phoneNumber: '123-456-7890',
  healthServices: [
    {
      name: 'PTSD care',
      vetCenterTypeOfCare: 'counseling',
      vetCenterFriendlyName: null,
      alsoKnownAs: null,
      vetCenterComConditions: null,
      commonlyTreatedCondition: null,
      vetCenterServiceDescription: 'PTSD counseling services.',
      body: '<p>Pittsburgh Vet Center offers individual and group counseling.</p>',
    },
    {
      name: 'Couples and family counseling',
      vetCenterTypeOfCare: 'referral',
      vetCenterFriendlyName: null,
      alsoKnownAs: null,
      vetCenterComConditions: null,
      commonlyTreatedCondition: null,
      vetCenterServiceDescription: 'Couples and family counseling.',
      body: '<p>Pittsburgh Vet Center counselors on-site.</p>',
    },
  ],
  counselingHealthServices: [],
  referralHealthServices: [],
  otherHealthServices: [],
  image: {
    id: '3d6716b3-fb66-4e63-9b21-bb9c024129d3',
    links: {
      '2_1_large': {
        href: 'https://s3-us-gov-west-1.amazonaws.com/content.www.va.gov/img/styles/2_1_large/public/2019-05/doctor-year2019-decker-480_0.jpg',
        meta: {
          linkParams: {
            width: 700,
            height: 350,
          },
        },
      },
    },
    alt: 'Smiling man in glasses.',
    title: '',
    width: 700,
    height: 350,
  },
  prepareForVisit: [],
  title: 'Test title',
  fieldFacilityLocatorApiId: 'Test API ID',
  path: '/test-vet-center/test-outstation',
  id: '1',
  type: 'node--vet_center_outstation' as const,
  published: true,
  lastUpdated: '',
  lastSavedByAnEditor: '',
  operatingStatusFacility: '',
  operatingStatusMoreInfo: null,
  timezone: '',
  administration: undefined as VetCenterOutstation['administration'],
}
