name: 'Login to Amazon ECR'
description: 'Auth steps for build process to use private docker images from VA's govcloud ECR'
inputs:
  aws-region:
    description: 'AWS region to auth to'
    required: true
    default: 'us-gov-west-1'
  role-to-assume:
    description: 'Which role to use for auth'
    required: true
    default: ${{ vars.AWS_ASSUME_ROLE }}

outputs:
  docker_username: ${{ steps.login-ecr.outputs.docker_username_008577686731_dkr_ecr_us_gov_west_1_amazonaws_com }}
  docker_password: ${{ steps.login-ecr.outputs.docker_password_008577686731_dkr_ecr_us_gov_west_1_amazonaws_com }}

runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.role-to-assume }}
        mask-aws-account-id: 'false'
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        mask-password: 'false'
