import { VamcSystemMedicalRecordsOffice } from './formatted-type'

const mockData: VamcSystemMedicalRecordsOffice = {
  id: 'b30bc647-2c0f-4d21-beb9-15b2097024f1',
  entityId: 45726,
  entityPath: '/boston-health-care/medical-records-office',
  type: 'node--vamc_system_medical_records_offi',
  published: true,
  moderationState: 'published',
  title: 'Medical records office',
  metatags: [],
  breadcrumbs: [
    {
      uri: 'https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/',
      title: 'Home',
      options: [],
    },
    {
      uri: 'https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/boston-health-care',
      title: 'VA Beckley health care',
      options: [],
    },
    {
      uri: 'internal:#',
      title: 'Medical records office',
      options: [],
    },
  ],
  lastUpdated: '2025-07-29T19:17:25+00:00',
  vamcSystem: {
    id: 'def03529-b07f-4e36-b3aa-e88ffeaa222a',
    title: 'VA Beckley health care',
  },
  menu: {
    rootPath: '/boston-health-care/medical-records-office/',
    data: {
      name: 'VA Beckley health care',
      description: null,
      links: [
        {
          description: null,
          expanded: false,
          label: 'VA Beckley health care',
          links: [
            {
              description: null,
              expanded: false,
              label: 'SERVICES AND LOCATIONS',
              links: [
                {
                  description: null,
                  expanded: false,
                  label: 'Health services',
                  links: [],
                  url: {
                    path: '/boston-health-care/health-services',
                  },
                  lovellSection: null,
                },
                {
                  description: null,
                  expanded: false,
                  label: 'Locations',
                  links: [
                    {
                      description: null,
                      expanded: false,
                      label: 'Brockton VA Medical Center',
                      links: [],
                      url: {
                        path: '/boston-health-care/locations/brockton-va-medical-center',
                      },
                      lovellSection: null,
                    },
                    {
                      description: null,
                      expanded: false,
                      label: 'Jamaica Plain VA Medical Center',
                      links: [],
                      url: {
                        path: '/boston-health-care/locations/jamaica-plain-va-medical-center',
                      },
                      lovellSection: null,
                    },
                    {
                      description: null,
                      expanded: false,
                      label: 'West Roxbury VA Medical Center',
                      links: [],
                      url: {
                        path: '/boston-health-care/locations/west-roxbury-va-medical-center',
                      },
                      lovellSection: null,
                    },
                    {
                      description: null,
                      expanded: false,
                      label: 'Causeway VA Clinic',
                      links: [],
                      url: {
                        path: '/boston-health-care/locations/causeway-va-clinic',
                      },
                      lovellSection: null,
                    },
                    {
                      description: null,
                      expanded: false,
                      label: 'Framingham VA Clinic',
                      links: [],
                      url: {
                        path: '/boston-health-care/locations/framingham-va-clinic',
                      },
                      lovellSection: null,
                    },
                    {
                      description: null,
                      expanded: false,
                      label: 'Lowell VA Clinic',
                      links: [],
                      url: {
                        path: '/boston-health-care/locations/lowell-va-clinic',
                      },
                      lovellSection: null,
                    },
                    {
                      description: null,
                      expanded: false,
                      label: 'Plymouth VA Clinic',
                      links: [],
                      url: {
                        path: '/boston-health-care/locations/plymouth-va-clinic',
                      },
                      lovellSection: null,
                    },
                    {
                      description: null,
                      expanded: false,
                      label: 'Quincy VA Clinic',
                      links: [],
                      url: {
                        path: '/boston-health-care/locations/quincy-va-clinic',
                      },
                      lovellSection: null,
                    },
                  ],
                  url: {
                    path: '/boston-health-care/locations',
                  },
                  lovellSection: null,
                },
              ],
              url: {
                path: '',
              },
              lovellSection: null,
            },
            {
              description: null,
              expanded: false,
              label: 'NEWS AND EVENTS',
              links: [
                {
                  description: null,
                  expanded: false,
                  label: 'Events',
                  links: [],
                  url: {
                    path: '/boston-health-care/events',
                  },
                  lovellSection: null,
                },
                {
                  description: null,
                  expanded: false,
                  label: 'News releases',
                  links: [],
                  url: {
                    path: '/boston-health-care/news-releases',
                  },
                  lovellSection: null,
                },
                {
                  description: null,
                  expanded: false,
                  label: 'Stories',
                  links: [],
                  url: {
                    path: '/boston-health-care/stories',
                  },
                  lovellSection: null,
                },
              ],
              url: {
                path: '',
              },
              lovellSection: null,
            },
            {
              description: null,
              expanded: false,
              label: 'ABOUT VA BOSTON',
              links: [
                {
                  description: null,
                  expanded: false,
                  label: 'About us',
                  links: [
                    {
                      description: null,
                      expanded: false,
                      label: 'Mission and vision',
                      links: [],
                      url: {
                        path: '/boston-health-care/about-us/mission-and-vision',
                      },
                      lovellSection: null,
                    },
                    {
                      description: null,
                      expanded: false,
                      label: 'History',
                      links: [],
                      url: {
                        path: '/boston-health-care/about-us/history',
                      },
                      lovellSection: null,
                    },
                    {
                      description: null,
                      expanded: false,
                      label: 'Performance',
                      links: [],
                      url: {
                        path: '/boston-health-care/about-us/performance',
                      },
                      lovellSection: null,
                    },
                    {
                      description: null,
                      expanded: false,
                      label: 'Leadership',
                      links: [],
                      url: {
                        path: '/boston-health-care/about-us/leadership',
                      },
                      lovellSection: null,
                    },
                  ],
                  url: {
                    path: '/boston-health-care/about-us',
                  },
                  lovellSection: null,
                },
                {
                  description: null,
                  expanded: false,
                  label: 'Policies',
                  links: [],
                  url: {
                    path: '/boston-health-care/policies',
                  },
                  lovellSection: null,
                },
                {
                  description: null,
                  expanded: false,
                  label: 'VA police',
                  links: [],
                  url: {
                    path: '/boston-health-care/va-police',
                  },
                  lovellSection: null,
                },
                {
                  description: null,
                  expanded: false,
                  label: 'Work with us',
                  links: [
                    {
                      description: null,
                      expanded: false,
                      label: 'Jobs and careers',
                      links: [
                        {
                          description: null,
                          expanded: false,
                          label: 'New Employee Information',
                          links: [],
                          url: {
                            path: '/boston-health-care/work-with-us/jobs-and-careers/new-employee-information',
                          },
                          lovellSection: null,
                        },
                        {
                          description: null,
                          expanded: false,
                          label: 'Nursing Careers',
                          links: [],
                          url: {
                            path: '/boston-health-care/work-with-us/jobs-and-careers/nursing-careers',
                          },
                          lovellSection: null,
                        },
                      ],
                      url: {
                        path: '/boston-health-care/work-with-us/jobs-and-careers',
                      },
                      lovellSection: null,
                    },
                    {
                      description: null,
                      expanded: false,
                      label: 'Internships and fellowships',
                      links: [
                        {
                          description: null,
                          expanded: false,
                          label:
                            'Hospital-based Medical Laboratory Science Program',
                          links: [],
                          url: {
                            path: '/boston-health-care/work-with-us/internships-and-fellowships/hospital-based-medical-laboratory-science-program',
                          },
                          lovellSection: null,
                        },
                        {
                          description: null,
                          expanded: false,
                          label: 'Faculty Development',
                          links: [
                            {
                              description: null,
                              expanded: false,
                              label:
                                'VA Boston Health Professions Educator Certificate',
                              links: [],
                              url: {
                                path: '/boston-health-care/work-with-us/internships-and-fellowships/faculty-development/va-boston-health-professions-educator-certificate',
                              },
                              lovellSection: null,
                            },
                            {
                              description: null,
                              expanded: false,
                              label: 'Newsletter',
                              links: [],
                              url: {
                                path: '/boston-health-care/work-with-us/internships-and-fellowships/faculty-development/newsletter',
                              },
                              lovellSection: null,
                            },
                          ],
                          url: {
                            path: '/boston-health-care/work-with-us/internships-and-fellowships/faculty-development',
                          },
                          lovellSection: null,
                        },
                        {
                          description: null,
                          expanded: false,
                          label: 'Grand Rounds',
                          links: [],
                          url: {
                            path: '/boston-health-care/work-with-us/internships-and-fellowships/grand-rounds',
                          },
                          lovellSection: null,
                        },
                        {
                          description: null,
                          expanded: false,
                          label: 'National VA Tele-Memory Clinic',
                          links: [],
                          url: {
                            path: '/boston-health-care/work-with-us/internships-and-fellowships/national-va-tele-memory-clinic',
                          },
                          lovellSection: null,
                        },
                        {
                          description: null,
                          expanded: false,
                          label: 'Trainee Programs',
                          links: [],
                          url: {
                            path: '/boston-health-care/work-with-us/internships-and-fellowships/trainee-programs',
                          },
                          lovellSection: null,
                        },
                        {
                          description: null,
                          expanded: false,
                          label: 'Trainee Resources',
                          links: [],
                          url: {
                            path: '/boston-health-care/work-with-us/internships-and-fellowships/trainee-resources',
                          },
                          lovellSection: null,
                        },
                        {
                          description: null,
                          expanded: false,
                          label: 'Whole Health Training',
                          links: [],
                          url: {
                            path: '/boston-health-care/work-with-us/internships-and-fellowships/whole-health-training',
                          },
                          lovellSection: null,
                        },
                        {
                          description: null,
                          expanded: false,
                          label: 'Psychology training programs',
                          links: [],
                          url: {
                            path: '/boston-health-care/work-with-us/internships-and-fellowships/psychology-training-programs',
                          },
                          lovellSection: null,
                        },
                        {
                          description: null,
                          expanded: false,
                          label: 'Nursing trainee programs',
                          links: [],
                          url: {
                            path: '/boston-health-care/work-with-us/internships-and-fellowships/nursing-affiliations-and-rnnp-residency-programs',
                          },
                          lovellSection: null,
                        },
                        {
                          description: null,
                          expanded: false,
                          label: 'Decision-Making Capacity',
                          links: [],
                          url: {
                            path: '/boston-health-care/work-with-us/internships-and-fellowships/decision-making-capacity',
                          },
                          lovellSection: null,
                        },
                        {
                          description: null,
                          expanded: false,
                          label: 'Education Academy Files',
                          links: [],
                          url: {
                            path: '/boston-health-care/work-with-us/internships-and-fellowships/education-academy-files',
                          },
                          lovellSection: null,
                        },
                        {
                          description: null,
                          expanded: false,
                          label: 'My Life, My Story',
                          links: [],
                          url: {
                            path: '/boston-health-care/work-with-us/internships-and-fellowships/my-life-my-story',
                          },
                          lovellSection: null,
                        },
                        {
                          description: null,
                          expanded: false,
                          label: 'Wellness',
                          links: [],
                          url: {
                            path: '/boston-health-care/work-with-us/internships-and-fellowships/faculty-development/wellness',
                          },
                          lovellSection: null,
                        },
                        {
                          description: null,
                          expanded: false,
                          label: 'Additional Resources',
                          links: [],
                          url: {
                            path: '/boston-health-care/work-with-us/internships-and-fellowships/faculty-development/additional-resources',
                          },
                          lovellSection: null,
                        },
                        {
                          description: null,
                          expanded: false,
                          label: 'CPRS',
                          links: [],
                          url: {
                            path: '/boston-health-care/work-with-us/internships-and-fellowships/cprs',
                          },
                          lovellSection: null,
                        },
                        {
                          description: null,
                          expanded: false,
                          label: 'EARS Resources',
                          links: [],
                          url: {
                            path: '/boston-health-care/work-with-us/internships-and-fellowships/ears-resources',
                          },
                          lovellSection: null,
                        },
                        {
                          description: null,
                          expanded: false,
                          label: 'Hospice and Palliative Medicine Fellowship',
                          links: [],
                          url: {
                            path: '/boston-health-care/work-with-us/internships-and-fellowships/hospice-and-palliative-medicine-fellowship',
                          },
                          lovellSection: null,
                        },
                        {
                          description: null,
                          expanded: false,
                          label: 'Nurse practitioner residency programs',
                          links: [],
                          url: {
                            path: '/boston-health-care/work-with-us/internships-and-fellowships/nurse-practitioner-residency-programs',
                          },
                          lovellSection: null,
                        },
                      ],
                      url: {
                        path: '/boston-health-care/work-with-us/internships-and-fellowships',
                      },
                      lovellSection: null,
                    },
                    {
                      description: null,
                      expanded: false,
                      label: 'Volunteer or donate',
                      links: [
                        {
                          description: null,
                          expanded: false,
                          label: 'Volunteer Assignment Training & Requirements',
                          links: [],
                          url: {
                            path: '/boston-health-care/work-with-us/volunteer-or-donate/volunteer-assignment-training-requirements',
                          },
                          lovellSection: null,
                        },
                      ],
                      url: {
                        path: '/boston-health-care/work-with-us/volunteer-or-donate',
                      },
                      lovellSection: null,
                    },
                  ],
                  url: {
                    path: '/boston-health-care/work-with-us',
                  },
                  lovellSection: null,
                },
                {
                  description: null,
                  expanded: false,
                  label: 'Contact us',
                  links: [],
                  url: {
                    path: '/boston-health-care/contact-us',
                  },
                  lovellSection: null,
                },
              ],
              url: {
                path: '',
              },
              lovellSection: null,
            },
          ],
          url: {
            path: '/boston-health-care',
          },
          lovellSection: null,
        },
      ],
    },
  },
  topOfPageContent: {
    type: 'paragraph--wysiwyg',
    id: '82634',
    html: '<h2 id="get-your-records-online">Get your records online</h2><p>Access your VA medical records online. Sign in to view, organize, and share your VA medical records and other personal health information.&nbsp;We don\'t charge any fees to send copies directly to health care providers.</p>',
  },
  getRecordsInPersonContent: {
    type: 'paragraph--wysiwyg',
    id: '82639',
    html: '<h2 id="get-your-records-in-person">Get your records in person</h2><p>We can help you get copies of your VA medical records. We can also help you update your records. Call or visit one of our release of information offices.</p><p><strong>What to bring</strong></p><ul><li>A signed written request for a copy of your records to be provided to you. For your convenience you may download and complete the “Individuals’ Request For a Copy of Their Own Health Information” (VA Form 10-5345a).  <a href="https://www.va.gov/vaforms/medical/pdf/VHA%20Form%2010-5345a%20Fill-revision.pdf" hreflang="en">Download VA Form 10-5345a (PDF)</a></li><li>Your Veteran Health Identification Card (VHIC)</li></ul>',
  },
  reactWidget: {
    type: 'paragraph--react_widget',
    id: '82635',
    entityId: null,
    widgetType: 'modern-get-medical-records-page',
    ctaWidget: true,
    loadingMessage: null,
    timeout: 20,
    errorMessage:
      '<strong>We’re sorry. Something went wrong when we tried to load your saved application.</strong><br>Please try refreshing your browser in a few minutes.',
    defaultLink: null,
    buttonFormat: false,
  },
  relatedLinks: {
    type: 'paragraph--list_of_link_teasers',
    id: '82659',
    entityId: null,
    title: 'More information',
    linkTeasers: [
      {
        type: 'paragraph--link_teaser',
        id: '82655',
        entityId: null,
        uri: '/resources/change-your-address-on-file-with-va',
        title: 'Change your address on file with VA',
        options: {
          href: 'entity:node/8473',
          'data-entity-type': 'node',
          'data-entity-uuid': '5f539c97-cfe7-4496-9dd5-a9b4d01f592d',
          'data-entity-substitution': 'canonical',
        },
        summary:
          'Find out how to change your address and other information in your VA.gov profile. This will update your information across several VA benefits and services.',
        parentField: null,
        componentParams: {
          sectionHeader: '',
        },
      },
      {
        type: 'paragraph--link_teaser',
        id: '82656',
        entityId: null,
        uri: '/health-care/update-health-information',
        title: 'Update your VA health benefits information',
        options: {
          href: 'entity:node/39',
          'data-entity-type': 'node',
          'data-entity-uuid': 'bcca7668-9a43-47ec-b029-e3563dc836f4',
          'data-entity-substitution': 'canonical',
        },
        summary:
          'Update your personal, financial, or insurance information with VA Form 10-10EZR.',
        parentField: null,
        componentParams: {
          sectionHeader: '',
        },
      },
      {
        type: 'paragraph--link_teaser',
        id: '82657',
        entityId: null,
        uri: '/records',
        title: 'Access and manage your records',
        options: {
          href: 'entity:node/79',
          'data-entity-type': 'node',
          'data-entity-uuid': 'be5ce8bb-48af-4ac0-bf45-124081bb3dcb',
          'data-entity-substitution': 'canonical',
        },
        summary:
          'Apply for a printed Veteran ID card, get your VA benefit letters and military service records, and learn how to apply for a discharge upgrade.',
        parentField: null,
        componentParams: {
          sectionHeader: '',
        },
      },
      {
        type: 'paragraph--link_teaser',
        id: '82658',
        entityId: null,
        uri: 'https://www.choose.va.gov/',
        title: 'MISSION Act and VA health care',
        options: {
          href: 'https://www.choose.va.gov/',
          'data-entity-type': '',
          'data-entity-uuid': '',
          'data-entity-substitution': '',
        },
        summary:
          "Learn how we're making it easier for you to get health care through VA facilities, mobile health clinics, virtual telehealth, and community care providers.",
        parentField: null,
        componentParams: {
          sectionHeader: '',
        },
      },
    ],
  },
  services: [
    {
      id: 'ae6021f9-d6ae-44f2-9652-e592d42cb306',
      title: 'Brockton VA Medical Center',
      path: '/boston-health-care/locations/brockton-va-medical-center',
      serviceLocations: [
        {
          type: 'paragraph--service_location',
          id: '01f89ae4-5905-4c6f-997e-7b91928c7de3',
          officeVisits: null,
          virtualSupport: null,
          apptIntroTextType: null,
          apptIntroTextCustom: null,
          appointmentPhoneNumbers: [],
          onlineSchedulingAvail: null,
          contactInfoPhoneNumbers: [
            {
              type: 'paragraph--phone_number',
              id: '9f7bcef7-bedc-42a4-af6c-d7072a0b8764',
              entityId: 145360,
              label: 'Fax number for signed VA Form 10-5345a',
              number: '774-826-1446',
              extension: null,
              phoneType: 'tel',
            },
          ],
          emailContacts: [],
          hours: '2',
          officeHours: [
            {
              day: 1,
              all_day: false,
              starthours: 800,
              endhours: 1630,
              comment: '',
            },
            {
              day: 2,
              all_day: false,
              starthours: 800,
              endhours: 1630,
              comment: '',
            },
            {
              day: 3,
              all_day: false,
              starthours: 800,
              endhours: 1630,
              comment: '',
            },
            {
              day: 4,
              all_day: false,
              starthours: 800,
              endhours: 1630,
              comment: '',
            },
            {
              day: 5,
              all_day: false,
              starthours: 800,
              endhours: 1630,
              comment: '',
            },
          ],
          additionalHoursInfo: null,
          useMainFacilityPhone: true,
          useFacilityPhoneNumber: false,
          serviceLocationAddress: {
            type: 'paragraph--service_location_address',
            id: '69f0cc8c-c20c-4674-b5f1-73a1f74f3bca',
            drupal_internal__id: 110371,
            drupal_internal__revision_id: 1825322,
            langcode: 'en',
            status: true,
            created: '2022-06-06T18:01:22+00:00',
            parent_id: '110372',
            parent_type: 'paragraph',
            parent_field_name: 'field_service_location_address',
            behavior_settings: [],
            default_langcode: true,
            revision_translation_affected: true,
            breadcrumbs: [],
            content_translation_source: 'und',
            content_translation_outdated: false,
            content_translation_changed: null,
            field_address: {
              langcode: 'en',
              country_code: 'US',
              administrative_area: '',
              locality: '',
              dependent_locality: null,
              postal_code: '',
              sorting_code: null,
              address_line1: '',
              address_line2: '',
            },
            field_building_name_number: 'Building 2',
            field_clinic_name: 'Medical records office - Brockton',
            field_use_facility_address: true,
            field_wing_floor_or_room_number: 'Basement, C-wing, C-010-C',
            links: {
              self: {
                href: 'https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/jsonapi/paragraph/service_location_address/69f0cc8c-c20c-4674-b5f1-73a1f74f3bca?resourceVersion=id%3A1825322',
              },
            },
            resourceIdObjMeta: {
              target_revision_id: 1825322,
              drupal_internal__target_id: 110371,
            },
            paragraph_type: {
              type: 'paragraphs_type--paragraphs_type',
              id: 'bd794386-a382-48d0-84fb-47290c3c1176',
              resourceIdObjMeta: {
                drupal_internal__target_id: 'service_location_address',
              },
            },
            relationshipNames: ['paragraph_type'],
          },
        },
      ],
      address: {
        langcode: 'en',
        country_code: 'US',
        administrative_area: 'MA',
        locality: 'Brockton',
        dependent_locality: null,
        postal_code: '02301-5596',
        address_line1: '940 Belmont Street',
      },
      phoneNumber: '508-583-4500',
    },
    {
      id: 'd4244451-917c-45f3-b25b-f98ebe207561',
      title: 'Jamaica Plain VA Medical Center',
      path: '/boston-health-care/locations/jamaica-plain-va-medical-center',
      serviceLocations: [
        {
          type: 'paragraph--service_location',
          id: 'bf4bd1af-611f-43e3-875b-8a19565d9ee9',
          officeVisits: null,
          virtualSupport: null,
          apptIntroTextType: null,
          apptIntroTextCustom: null,
          appointmentPhoneNumbers: [],
          onlineSchedulingAvail: null,
          contactInfoPhoneNumbers: [
            {
              type: 'paragraph--phone_number',
              id: '88f56526-51f7-4fa4-9841-9c9d6111e39e',
              entityId: 145357,
              label: 'Fax number for signed VA Form 10-5345a ',
              number: '857-364-4495',
              extension: null,
              phoneType: 'tel',
            },
          ],
          emailContacts: [],
          hours: '2',
          officeHours: [
            {
              day: 1,
              all_day: false,
              starthours: 800,
              endhours: 1600,
              comment: '',
            },
            {
              day: 2,
              all_day: false,
              starthours: 800,
              endhours: 1600,
              comment: '',
            },
            {
              day: 3,
              all_day: false,
              starthours: 800,
              endhours: 1600,
              comment: '',
            },
            {
              day: 4,
              all_day: false,
              starthours: 800,
              endhours: 1600,
              comment: '',
            },
            {
              day: 5,
              all_day: false,
              starthours: 800,
              endhours: 1600,
              comment: '',
            },
          ],
          additionalHoursInfo:
            'All campuses can provide records for all VA Boston Healthcare System facilities. Lawyers and insurance companies only need to submit one request to a single office to get records from all of VA Boston HCS.',
          useMainFacilityPhone: true,
          useFacilityPhoneNumber: false,
          serviceLocationAddress: {
            type: 'paragraph--service_location_address',
            id: '4ef86bc3-9204-467a-bc7a-1bb803e7f0ff',
            drupal_internal__id: 110373,
            drupal_internal__revision_id: 1825496,
            langcode: 'en',
            status: true,
            created: '2022-06-06T18:11:40+00:00',
            parent_id: '110374',
            parent_type: 'paragraph',
            parent_field_name: 'field_service_location_address',
            behavior_settings: [],
            default_langcode: true,
            revision_translation_affected: true,
            breadcrumbs: [],
            content_translation_source: 'und',
            content_translation_outdated: false,
            content_translation_changed: null,
            field_address: {
              langcode: 'en',
              country_code: 'US',
              administrative_area: '',
              locality: '',
              dependent_locality: null,
              postal_code: '',
              sorting_code: null,
              address_line1: '',
              address_line2: '',
            },
            field_building_name_number: 'Building 1',
            field_clinic_name: 'Medical records office - JP',
            field_use_facility_address: true,
            field_wing_floor_or_room_number: 'Basement, B-wing, DB-112',
            links: {
              self: {
                href: 'https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/jsonapi/paragraph/service_location_address/4ef86bc3-9204-467a-bc7a-1bb803e7f0ff?resourceVersion=id%3A1825496',
              },
            },
            resourceIdObjMeta: {
              target_revision_id: 1825496,
              drupal_internal__target_id: 110373,
            },
            paragraph_type: {
              type: 'paragraphs_type--paragraphs_type',
              id: 'bd794386-a382-48d0-84fb-47290c3c1176',
              resourceIdObjMeta: {
                drupal_internal__target_id: 'service_location_address',
              },
            },
            relationshipNames: ['paragraph_type'],
          },
        },
      ],
      address: {
        langcode: 'en',
        country_code: 'US',
        administrative_area: 'MA',
        locality: 'Boston',
        dependent_locality: null,
        postal_code: '02130-4817',
        address_line1: '150 South Huntington Avenue',
      },
      phoneNumber: '617-232-9500',
    },
    {
      id: 'ee20df88-eea2-4965-9e73-8e6d2de71815',
      title: 'West Roxbury VA Medical Center',
      path: '/boston-health-care/locations/west-roxbury-va-medical-center',
      serviceLocations: [
        {
          type: 'paragraph--service_location',
          id: 'ef35e811-bab5-4950-9995-322e90013d34',
          officeVisits: null,
          virtualSupport: null,
          apptIntroTextType: null,
          apptIntroTextCustom: null,
          appointmentPhoneNumbers: [],
          onlineSchedulingAvail: null,
          contactInfoPhoneNumbers: [
            {
              type: 'paragraph--phone_number',
              id: '6af40fb3-8731-4dd3-9a21-746c8bdd1e63',
              entityId: 145359,
              label: 'Fax number for signed VA Form 10-5345a',
              number: '857-203-5630',
              extension: null,
              phoneType: 'tel',
            },
          ],
          emailContacts: [],
          hours: '2',
          officeHours: [
            {
              day: 1,
              all_day: false,
              starthours: 800,
              endhours: 1630,
              comment: '',
            },
            {
              day: 2,
              all_day: false,
              starthours: 800,
              endhours: 1630,
              comment: '',
            },
            {
              day: 3,
              all_day: false,
              starthours: 800,
              endhours: 1630,
              comment: '',
            },
            {
              day: 4,
              all_day: false,
              starthours: 800,
              endhours: 1630,
              comment: '',
            },
            {
              day: 5,
              all_day: false,
              starthours: 800,
              endhours: 1630,
              comment: '',
            },
          ],
          additionalHoursInfo: null,
          useMainFacilityPhone: true,
          useFacilityPhoneNumber: false,
          serviceLocationAddress: {
            type: 'paragraph--service_location_address',
            id: 'c58fe4ce-709a-45ef-882d-bc1ea5b02f3c',
            drupal_internal__id: 110375,
            drupal_internal__revision_id: 1825490,
            langcode: 'en',
            status: true,
            created: '2022-06-06T18:16:01+00:00',
            parent_id: '110376',
            parent_type: 'paragraph',
            parent_field_name: 'field_service_location_address',
            behavior_settings: [],
            default_langcode: true,
            revision_translation_affected: true,
            breadcrumbs: [],
            content_translation_source: 'und',
            content_translation_outdated: false,
            content_translation_changed: null,
            field_address: {
              langcode: 'en',
              country_code: 'US',
              administrative_area: '',
              locality: '',
              dependent_locality: null,
              postal_code: '',
              sorting_code: null,
              address_line1: '',
              address_line2: '',
            },
            field_building_name_number: 'Building 1',
            field_clinic_name: 'Medical records office - West Roxbury',
            field_use_facility_address: true,
            field_wing_floor_or_room_number: 'Ground floor, B-wing, GB-104',
            links: {
              self: {
                href: 'https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/jsonapi/paragraph/service_location_address/c58fe4ce-709a-45ef-882d-bc1ea5b02f3c?resourceVersion=id%3A1825490',
              },
            },
            resourceIdObjMeta: {
              target_revision_id: 1825490,
              drupal_internal__target_id: 110375,
            },
            paragraph_type: {
              type: 'paragraphs_type--paragraphs_type',
              id: 'bd794386-a382-48d0-84fb-47290c3c1176',
              resourceIdObjMeta: {
                drupal_internal__target_id: 'service_location_address',
              },
            },
            relationshipNames: ['paragraph_type'],
          },
        },
      ],
      address: {
        langcode: null,
        country_code: 'US',
        administrative_area: 'MA',
        locality: 'West Roxbury',
        dependent_locality: null,
        postal_code: '02132-4927',
        address_line1: '1400 VFW Parkway',
      },
      phoneNumber: '617-323-7700',
    },
  ],
  lovellVariant: null,
  lovellSwitchPath: null,
}

export default mockData
