name: Continuous Integration
on:
  push:
    branches:
      - 'main'
  pull_request:
permissions:
  pull-requests: write
  issues: write

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@cd7d8d697e10461458bc61a30d094dc601a8b017
        with:
          fetch-depth: 0

      - name: Dependency Review
        uses: actions/dependency-review-action@2031cfc080254a8a887f58cffee85186f0e49e48
        with:
          base-ref: main
          head-ref: ${{ github.sha }}
          fail-on-severity: moderate
          fail-on-scopes: runtime, development
          comment-summary-in-pr: on-failure
          license-check: false
  
  check-typescript:
    name: Check TypeScript
    needs: [dependency-review]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc

      - name: Install Npm Dependencies
        run: |
          yarn set version 3.6.1
          HUSKY=0 yarn install --immutable

      - name: Check TypeScript
        run: yarn test:types

  run-lint:
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc

      - name: Install Npm Dependencies
        run: |
          yarn set version 3.6.1
          HUSKY=0 yarn install --immutable

      - name: Run Lint
        run: yarn lint

  check-format:
    name: Check Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc

      - name: Install Npm Dependencies
        run: |
          yarn set version 3.6.1
          HUSKY=0 yarn install --immutable

      - name: Check format
        run: yarn test:format

  jest-tests:
    name: Jest Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc

      - name: Install Npm Dependencies
        run: |
          yarn set version 3.6.1
          HUSKY=0 yarn install --immutable

      - name: Jest tests
        run: yarn test:ci
