name: recurring release
on:
    workflow_dispatch:
    
    schedule:
        - cron: "*/30 8-20 * * 1-5" # run a build to prod every 30 minutes from 8am to 8pm monday to friday
          
jobs:
    content-release:
        uses: department-of-veterans-affairs/next-build/.github/workflows/content-release.yml@main
        with:
            build_type: "prod"
        secrets: inherit
        
    content-release-dev:
        uses: department-of-veterans-affairs/next-build/.github/workflows/content-release.yml@main
        with:
            build_type: "dev"
        secrets: inherit
    
    content-release-staging:
        uses: department-of-veterans-affairs/next-build/.github/workflows/content-release.yml@main
        with:
            build_type: "staging"
        secrets: inherit
        

