name: CI - Test
on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  test:
    name: Setup
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16.13.0'
          check-latest: true

      - name: Install Npm Dependencies
        run: yarn install

      # - name: Check TypeScript
      #   run: yarn test:types

      - name: Run Lint
        run: yarn lint

      - name: Check format
        run: yarn test:format

      - name: Run tests with jest
        run: yarn test:ci

      # - name: Cypress.io
      #   uses: cypress-io/github-action@v2
      #   with:
      #     start: yarn start
      #     wait-on: 'http://localhost:3000'
